# Generated by Django 5.1.15 on 2026-01-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cosplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título del Cosplay')),
                ('image', models.ImageField(upload_to='cosplays/', verbose_name='Foto')),
                ('category', models.CharField(choices=[('LOAN', 'Loan'), ('BELA', 'Bela'), ('DUO', 'Loan + Bela')], default='LOAN', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cosplay',
                'verbose_name_plural': 'Cosplays',
            },
        ),
    ]
